// Writes .dev.vars for `wrangler dev` with freshly generated local-only
// values and prints the owner token once. .dev.vars is gitignored; nothing
// here is a production secret, and no value is reused anywhere.
//
//   npm run cf:dev-vars

import { existsSync, writeFileSync } from 'node:fs';
import { createHash, randomBytes } from 'node:crypto';

const path = '.dev.vars';
if (existsSync(path) && !process.argv.includes('--force')) {
  console.error(`${path} already exists. Rerun with --force to replace it.`);
  process.exit(1);
}
const ownerToken = randomBytes(32).toString('hex');
const pepper = randomBytes(32).toString('hex');
writeFileSync(
  path,
  [
    '# Local wrangler dev values, generated by scripts/cf-dev-vars.ts. Do not commit.',
    `OWNER_TOKEN_SHA256=${createHash('sha256').update(ownerToken).digest('hex')}`,
    `TOKEN_PEPPER=${pepper}`,
    '',
  ].join('\n'),
  { mode: 0o600 },
);
console.log(`Wrote ${path}. Local owner token (shown once; paste into /admin):\n${ownerToken}`);
